### ISSUE TITLE
Logs spams by error message

### ISSUE THREAD

**Issue by PoVPoV29** [Minims/SomfyProtect2MQTT#42] opened 2022-05-17 18:35 UTC
Hello,
The logs are spam by the following error message : 
2022-05-17 17:49:56 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.camera_cuisine_video_mode: 'HD' (valid options: ['FHD'])
HD is a valid option (FHD, HD and SD)
Can you correct that ?
Thanks.
Regards

**Comment by Minims** [comment] 2022-05-17 18:37
Hello,

This has been corrected but the add-on is broken for now. Wait until tomorrow to update

**Comment by Minims** [comment] 2022-05-18 19:09
Can you confirm the issue is fixed with the addon version : 0.1.9.8
repo :  https://github.com/Minims/homeassistant-addons

[![Open your Home Assistant instance and show the add add-on repository dialog with a specific repository URL pre-filled.](https://my.home-assistant.io/badges/supervisor_add_addon_repository.svg)](https://my.home-assistant.io/redirect/supervisor_add_addon_repository/?repository_url=https%3A%2F%2Fgithub.com%2FMinims%2Fhomeassistant-addons)

**Closed** 2022-05-23 20:27 UTC
